/* brain-king 题库：完全本地、原创表述、简体中文。 */
(function (root, factory) {
  'use strict';
  var q = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = q;
  }
  if (root) {
    root.BRAIN_KING_QUESTIONS = q;
  }
})(typeof self !== 'undefined' ? self : (typeof window !== 'undefined' ? window : this), function () {
  'use strict';
  return [
    /* ================= 生活常识与安全 60 ================= */
    { id: 'life001', category: '生活常识与安全', difficulty: '简单', question: '下雨天外出最好带什么？', options: ['雨伞', '风扇', '台灯', '扫帚'], answer: '雨伞', explanation: '下雨天带雨伞可以挡雨，避免淋湿着凉。' },
    { id: 'life002', category: '生活常识与安全', difficulty: '简单', question: '过马路时应走哪里？', options: ['斑马线', '马路中间', '车流中', '草坪上'], answer: '斑马线', explanation: '斑马线是专为行人横过马路设置的安全通道。' },
    { id: 'life003', category: '生活常识与安全', difficulty: '简单', question: '小朋友晚上睡觉前最好做什么？', options: ['刷牙', '吃糖', '玩游戏到很晚', '不洗脸'], answer: '刷牙', explanation: '睡前刷牙可以清洁牙齿，预防蛀牙。' },
    { id: 'life004', category: '生活常识与安全', difficulty: '简单', question: '吃水果前应该怎么做？', options: ['先清洗干净', '直接吃', '放很久再吃', '用脏手拿'], answer: '先清洗干净', explanation: '水果表面有灰尘和细菌，洗干净再吃才卫生。' },
    { id: 'life005', category: '生活常识与安全', difficulty: '简单', question: '看到红灯亮起时应该怎么做？', options: ['停下来等待', '快速冲过去', '慢慢往前走', '大声喊叫'], answer: '停下来等待', explanation: '红灯代表停止，要等绿灯亮了再安全通过。' },
    { id: 'life006', category: '生活常识与安全', difficulty: '简单', question: '上完厕所后应该做什么？', options: ['洗手', '直接吃饭', '不洗手', '擦嘴'], answer: '洗手', explanation: '上完厕所手上有细菌，洗手能防止病从口入。' },
    { id: 'life007', category: '生活常识与安全', difficulty: '简单', question: '冬天多穿衣服主要为了什么？', options: ['保暖', '好看', '变重', '挡雨'], answer: '保暖', explanation: '冬天天气冷，多穿衣服可以减少热量散失，保持体温。' },
    { id: 'life008', category: '生活常识与安全', difficulty: '简单', question: '打喷嚏时最好怎么做？', options: ['用手肘或纸巾捂住口鼻', '对着别人打', '不捂口鼻', '对着食物打'], answer: '用手肘或纸巾捂住口鼻', explanation: '捂住口鼻可以防止飞沫传播细菌，保护他人。' },
    { id: 'life009', category: '生活常识与安全', difficulty: '简单', question: '垃圾应该扔进哪里？', options: ['垃圾桶', '河里', '路边', '别人家门口'], answer: '垃圾桶', explanation: '把垃圾扔进垃圾桶才能保持环境整洁卫生。' },
    { id: 'life010', category: '生活常识与安全', difficulty: '简单', question: '家里电器着火时首先应该怎么做？', options: ['先断电再处理', '往火上泼水', '用手去扑', '跑开不管'], answer: '先断电再处理', explanation: '先切断电源可防止触电和火势扩大，再请大人处理。' },
    { id: 'life011', category: '生活常识与安全', difficulty: '简单', question: '口渴时最好喝什么？', options: ['白开水', '很烫的水', '脏水', '大量汽水'], answer: '白开水', explanation: '白开水干净卫生，是解渴补水的最好选择。' },
    { id: 'life012', category: '生活常识与安全', difficulty: '简单', question: '外出玩耍走丢了，正确的做法是？', options: ['找穿制服的工作人员或警察', '跟陌生人走', '哭闹乱跑', '躲起来不说话'], answer: '找穿制服的工作人员或警察', explanation: '找穿制服的警察或工作人员求助是安全可靠的做法。' },
    { id: 'life013', category: '生活常识与安全', difficulty: '简单', question: '过马路时为什么要看两边？', options: ['确认没有来车', '看风景', '数车子', '找朋友'], answer: '确认没有来车', explanation: '看两边能及时发现来车，确保安全后再通过。' },
    { id: 'life014', category: '生活常识与安全', difficulty: '简单', question: '夏天在户外玩得太热感觉中暑时，应该怎么做？', options: ['到阴凉处休息并补充水分', '继续暴晒', '剧烈运动', '喝很烫的水'], answer: '到阴凉处休息并补充水分', explanation: '到阴凉处休息并喝水能帮助身体降温，缓解中暑。' },
    { id: 'life015', category: '生活常识与安全', difficulty: '简单', question: '下面哪种坐姿是正确的？', options: ['背挺直、脚放平', '趴在桌子上', '斜躺着写作业', '驼着背'], answer: '背挺直、脚放平', explanation: '坐直可以保护脊柱和眼睛，防止近视和驼背。' },
    { id: 'life016', category: '生活常识与安全', difficulty: '简单', question: '吃饭前要先做什么？', options: ['洗手', '跑跳', '大声说话', '玩玩具'], answer: '洗手', explanation: '饭前洗手能洗掉手上的细菌，吃得才健康。' },
    { id: 'life017', category: '生活常识与安全', difficulty: '简单', question: '乘电梯时如果门正要关上，应该怎么做？', options: ['等下一趟', '用手挡门', '硬挤进去', '用脚踢门'], answer: '等下一趟', explanation: '用身体挡门或硬挤都很危险，等下一趟最安全。' },
    { id: 'life018', category: '生活常识与安全', difficulty: '简单', question: '把被子拿到太阳下晒，主要是为了什么？', options: ['杀菌去潮', '让被子变色', '让被子变厚', '赶走小鸟'], answer: '杀菌去潮', explanation: '阳光能晒干潮气并杀灭部分细菌，被子更蓬松健康。' },
    { id: 'life019', category: '生活常识与安全', difficulty: '简单', question: '眼睛累了看看远处的绿色植物，主要作用是什么？', options: ['放松眼睛', '增加视力', '让眼睛变色', '让眼睛更累'], answer: '放松眼睛', explanation: '看远处能让眼部肌肉放松，缓解用眼疲劳。' },
    { id: 'life020', category: '生活常识与安全', difficulty: '简单', question: '运动前做准备活动（热身）主要是为了什么？', options: ['防止受伤', '浪费时间', '让自己更累', '没有作用'], answer: '防止受伤', explanation: '热身能活动关节和肌肉，减少运动时受伤的可能。' },
    { id: 'life021', category: '生活常识与安全', difficulty: '简单', question: '起床后打开窗户是为了什么？', options: ['通风换气', '让房间变冷', '挡住阳光', '隔音'], answer: '通风换气', explanation: '开窗能让新鲜空气进来，排出房间里的闷气。' },
    { id: 'life022', category: '生活常识与安全', difficulty: '简单', question: '喝牛奶主要是为了补充哪种营养？', options: ['钙', '盐', '辣椒', '醋'], answer: '钙', explanation: '牛奶富含钙，有助于小朋友骨骼和牙齿的发育。' },
    { id: 'life023', category: '生活常识与安全', difficulty: '简单', question: '洗衣服时，深色和浅色的衣服最好怎么处理？', options: ['分开洗', '一起洗', '不洗', '只用水冲一下'], answer: '分开洗', explanation: '深色浅色分开洗可以防止浅色衣服被染色。' },
    { id: 'life024', category: '生活常识与安全', difficulty: '简单', question: '生病发烧时应该怎么做？', options: ['及时告诉家长并休息', '隐瞒不说', '继续剧烈运动', '自己乱吃药'], answer: '及时告诉家长并休息', explanation: '生病要及时告诉家长，在家长帮助下休息或就医。' },
    { id: 'life025', category: '生活常识与安全', difficulty: '中等', question: '如果看到有人溺水，你应该怎么做？', options: ['大声呼救并找大人帮忙', '自己跳下水救', '用棍子乱戳', '站在旁边看着'], answer: '大声呼救并找大人帮忙', explanation: '小朋友不能贸然下水，要尽快呼救请大人施救。' },
    { id: 'life026', category: '生活常识与安全', difficulty: '中等', question: '发现家里有煤气泄漏的气味时，首先应该怎么做？', options: ['开窗通风并关紧阀门', '开灯查看', '马上打电话', '点火测试'], answer: '开窗通风并关紧阀门', explanation: '开窗通风能稀释煤气，关紧阀门可阻止继续泄漏。' },
    { id: 'life027', category: '生活常识与安全', difficulty: '中等', question: '被烫伤后，正确的初步处理是？', options: ['用流动凉水冲洗', '涂牙膏', '抹酱油', '戳破水泡'], answer: '用流动凉水冲洗', explanation: '用凉水冲可以降温止痛，减少烫伤伤害。' },
    { id: 'life028', category: '生活常识与安全', difficulty: '中等', question: '我国的火警电话是哪个？', options: ['119', '110', '120', '114'], answer: '119', explanation: '119 是火警电话，遇到火灾时拨打求助。' },
    { id: 'life029', category: '生活常识与安全', difficulty: '中等', question: '我国的急救电话是哪个？', options: ['120', '110', '119', '122'], answer: '120', explanation: '120 是急救电话，有人受伤生病时拨打叫救护车。' },
    { id: 'life030', category: '生活常识与安全', difficulty: '中等', question: '我国的报警电话是哪个？', options: ['110', '120', '119', '121'], answer: '110', explanation: '110 是报警电话，遇到危险或需要警察帮助时拨打。' },
    { id: 'life031', category: '生活常识与安全', difficulty: '中等', question: '陌生人给你糖果要你跟他走，你应该怎么做？', options: ['拒绝并尽快离开，告诉家长', '接受并跟他走', '让陌生人帮忙带路', '原地站着不动'], answer: '拒绝并尽快离开，告诉家长', explanation: '不能跟陌生人走，要拒绝并离开，及时告诉家长。' },
    { id: 'life032', category: '生活常识与安全', difficulty: '中等', question: '过马路时突然有车驶来，正确的做法是？', options: ['在安全区等待车辆通过', '加速跑过去', '挡在车前', '跳起来'], answer: '在安全区等待车辆通过', explanation: '站在安全的地方等车通过，不要抢行或挡车。' },
    { id: 'life033', category: '生活常识与安全', difficulty: '中等', question: '给手机充电时，正确的做法是？', options: ['不要边充边玩', '放在枕头下充电', '用湿手插拔', '长时间空充'], answer: '不要边充边玩', explanation: '边充边玩会让电池过热，有安全隐患。' },
    { id: 'life034', category: '生活常识与安全', difficulty: '中等', question: '游泳时腿抽筋了，应该怎么做？', options: ['保持冷静，呼救或抓牢池边', '拼命乱蹬', '潜到水底', '大声哭闹'], answer: '保持冷静，呼救或抓牢池边', explanation: '保持冷静、抓牢池边并呼救，避免慌乱呛水。' },
    { id: 'life035', category: '生活常识与安全', difficulty: '中等', question: '电梯困人时，正确的做法是？', options: ['按紧急通话按钮求助', '用力扒门', '往上跳', '从顶部爬出'], answer: '按紧急通话按钮求助', explanation: '按紧急通话按钮联系工作人员，等专业人员救援。' },
    { id: 'life036', category: '生活常识与安全', difficulty: '中等', question: '为什么不能用湿手去摸电器开关？', options: ['水会导电，容易触电', '水会发热', '会弄脏开关', '没有原因'], answer: '水会导电，容易触电', explanation: '水是导体，湿手摸开关容易触电受伤。' },
    { id: 'life037', category: '生活常识与安全', difficulty: '中等', question: '食物发霉了应该怎么处理？', options: ['扔掉不吃', '把霉切掉继续吃', '加热后吃', '给宠物吃'], answer: '扔掉不吃', explanation: '发霉食物有霉菌毒素，切掉或加热也无法消除，要扔掉。' },
    { id: 'life038', category: '生活常识与安全', difficulty: '中等', question: '雷雨天气在户外时，应该怎么做？', options: ['远离大树和金属物', '在大树下躲雨', '举着金属杆', '站在水洼里'], answer: '远离大树和金属物', explanation: '大树和金属物容易引来雷电，要远离它们。' },
    { id: 'life039', category: '生活常识与安全', difficulty: '中等', question: '为什么要走人行横道（斑马线）过马路？', options: ['那里专为行人设置，更安全', '那里车更少', '那里好看', '随便走哪里都行'], answer: '那里专为行人设置，更安全', explanation: '人行横道是专为行人过马路设置的安全通道。' },
    { id: 'life040', category: '生活常识与安全', difficulty: '中等', question: '吃鱼的时候应该怎么做？', options: ['小心鱼刺，细嚼慢咽', '大口吞下', '边玩边吃', '快速咽下去'], answer: '小心鱼刺，细嚼慢咽', explanation: '鱼可能有刺，细嚼慢咽可以避免卡到喉咙。' },
    { id: 'life041', category: '生活常识与安全', difficulty: '中等', question: '在商场里和家人走散了，最好的求助对象是？', options: ['商场工作人员或保安', '随便哪个陌生人', '一个人乱找', '跑出商场'], answer: '商场工作人员或保安', explanation: '商场工作人员熟悉环境且可靠，找他们帮忙最安全。' },
    { id: 'life042', category: '生活常识与安全', difficulty: '中等', question: '为什么睡觉前要关灯？', options: ['光线会影响睡眠', '省钱但没必要', '让眼睛变更好', '关灯好玩'], answer: '光线会影响睡眠', explanation: '黑暗环境有助于身体放松，睡眠质量更好。' },
    { id: 'life043', category: '生活常识与安全', difficulty: '中等', question: '骑自行车或滑板上路时，正确的做法是？', options: ['戴好头盔并注意安全', '双手脱把', '戴耳机听歌', '在马路中央骑行'], answer: '戴好头盔并注意安全', explanation: '戴头盔能保护头部，专注骑行才能保证安全。' },
    { id: 'life044', category: '生活常识与安全', difficulty: '中等', question: '家里的药品应该怎么存放？', options: ['放在小朋友够不到的地方', '放在床边随手拿', '和食物混放', '敞开随意放'], answer: '放在小朋友够不到的地方', explanation: '药品要放在儿童够不到的地方，防止误服。' },
    { id: 'life045', category: '生活常识与安全', difficulty: '困难', question: '发生火灾需要逃生时，正确的做法是？', options: ['弯腰低姿，用湿毛巾捂住口鼻', '站着直着跑', '乘电梯下楼', '躲进衣柜'], answer: '弯腰低姿，用湿毛巾捂住口鼻', explanation: '烟雾向上飘，弯腰并用湿毛巾捂口鼻能减少吸入烟雾。' },
    { id: 'life046', category: '生活常识与安全', difficulty: '困难', question: '为什么火灾逃生时不能乘坐电梯？', options: ['火灾可能断电，电梯会困人', '电梯太快', '电梯太挤', '电梯会着火'], answer: '火灾可能断电，电梯会困人', explanation: '火灾容易断电，电梯停在半空会把人困在里面。' },
    { id: 'life047', category: '生活常识与安全', difficulty: '困难', question: '发生地震时如果来不及跑到室外，应该怎么做？', options: ['躲在结实的桌子下护住头部', '站在窗户旁', '跑进电梯', '从窗户跳下'], answer: '躲在结实的桌子下护住头部', explanation: '躲在结实桌子下并护住头，可以防止被掉落物砸伤。' },
    { id: 'life048', category: '生活常识与安全', difficulty: '困难', question: '发现家中电器发出焦味时，应该怎么做？', options: ['立即断电并请大人检查', '继续使用', '用水冲洗', '用布盖住'], answer: '立即断电并请大人检查', explanation: '焦味可能表示电器过热短路，要先断电再检查。' },
    { id: 'life049', category: '生活常识与安全', difficulty: '困难', question: '燃气灶火焰变成黄色（异常）时，说明什么？', options: ['燃烧不充分，可能存在隐患', '燃气充足', '火更旺更好', '完全正常'], answer: '燃烧不充分，可能存在隐患', explanation: '黄色火焰表示燃烧不充分，可能有一氧化碳隐患，要请人检查。' },
    { id: 'life050', category: '生活常识与安全', difficulty: '困难', question: '如果闻到家里有煤气味，绝对不能做的事是？', options: ['开灯或点火', '开窗通风', '关门后离开', '告诉大人'], answer: '开灯或点火', explanation: '开灯或点火可能产生火花引爆煤气，非常危险。' },
    { id: 'life051', category: '生活常识与安全', difficulty: '困难', question: '被动物咬伤后，正确的做法是？', options: ['及时用清水冲洗并尽快就医', '用嘴吸伤口', '往伤口涂泥土', '不管它'], answer: '及时用清水冲洗并尽快就医', explanation: '冲洗伤口并尽快就医，可降低感染和得狂犬病的风险。' },
    { id: 'life052', category: '生活常识与安全', difficulty: '困难', question: '为什么雷雨天不能在大树下避雨？', options: ['大树容易被雷电击中', '树下太晒', '树下有蛇', '树下太暗'], answer: '大树容易被雷电击中', explanation: '大树突出高耸，容易成为雷电击中的目标。' },
    { id: 'life053', category: '生活常识与安全', difficulty: '困难', question: '过马路前最安全的观察顺序是？', options: ['先看左再看右，确认安全再通过', '只看前方', '闭着眼睛通过', '边跑边看'], answer: '先看左再看右，确认安全再通过', explanation: '先看左边再看右边来车，确认安全后再通过最稳妥。' },
    { id: 'life054', category: '生活常识与安全', difficulty: '困难', question: '高层住宅发生火灾时，应该沿什么逃生？', options: ['安全通道楼梯向下走', '电梯', '窗户爬出', '阳台跳下'], answer: '安全通道楼梯向下走', explanation: '走安全楼梯向下撤离，不要乘坐电梯或跳楼。' },
    { id: 'life055', category: '生活常识与安全', difficulty: '困难', question: '吃东西被噎住且无法缓解时，应该怎么做？', options: ['立即寻求大人帮助并拨打急救电话', '继续吃东西', '用力蹦跳不管', '喝大量水'], answer: '立即寻求大人帮助并拨打急救电话', explanation: '噎住情况危险，要马上找大人并拨打急救电话求助。' },
    { id: 'life056', category: '生活常识与安全', difficulty: '困难', question: '为什么不能用饮料瓶长时间储存清洁剂？', options: ['可能被误当成饮料喝掉', '饮料瓶会坏', '清洁剂会冻住', '没有原因'], answer: '可能被误当成饮料喝掉', explanation: '用饮料瓶装清洁剂容易被误饮，非常危险。' },
    { id: 'life057', category: '生活常识与安全', difficulty: '困难', question: '正确的刷牙方式是？', options: ['上下竖刷，刷到每个牙面', '只刷门牙', '横着用力来回拉', '不刷舌头'], answer: '上下竖刷，刷到每个牙面', explanation: '上下竖刷、面面俱到才能把牙齿刷干净。' },
    { id: 'life058', category: '生活常识与安全', difficulty: '困难', question: '乘坐汽车时，小朋友应该坐在哪里？', options: ['后排并系好安全带', '副驾驶抱在大人腿上', '站在座位中间', '把头伸出窗外'], answer: '后排并系好安全带', explanation: '坐在后排系好安全带是最安全的乘车方式。' },
    { id: 'life059', category: '生活常识与安全', difficulty: '困难', question: '天黑后独自遇到可疑陌生人搭讪，应该怎么做？', options: ['快速走到人多的亮处并求助', '原地站着聊天', '跟他去偏僻处', '捂住耳朵不动'], answer: '快速走到人多的亮处并求助', explanation: '走到人多的明亮处并向大人求助，能保护自己。' },
    { id: 'life060', category: '生活常识与安全', difficulty: '困难', question: '为什么饭前便后要洗手？', options: ['减少细菌进入体内的机会', '让手变白', '让手变香', '没有作用'], answer: '减少细菌进入体内的机会', explanation: '洗手能洗掉手上细菌，防止它们跟着食物进入身体。' },
    /* ================= 自然科学与科普 60 ================= */
    { id: 'sci001', category: '自然科学与科普', difficulty: '简单', question: '太阳每天从哪个方向升起？', options: ['东方', '西方', '北方', '南方'], answer: '东方', explanation: '地球自转，我们看到的太阳每天从东方升起。' },
    { id: 'sci002', category: '自然科学与科普', difficulty: '简单', question: '地球围绕着什么转？', options: ['太阳', '月亮', '火星', '木星'], answer: '太阳', explanation: '地球绕太阳公转，绕着转一圈就是一年。' },
    { id: 'sci003', category: '自然科学与科普', difficulty: '简单', question: '月亮本身会发光吗？', options: ['不会，它反射太阳光', '会自己发光', '反射地球的光', '不发光但发热'], answer: '不会，它反射太阳光', explanation: '月亮本身不发光，我们看到的光是它反射的太阳光。' },
    { id: 'sci004', category: '自然科学与科普', difficulty: '简单', question: '下面哪种动物是我国的国宝？', options: ['大熊猫', '老虎', '狮子', '大象'], answer: '大熊猫', explanation: '大熊猫是我国特有的珍稀动物，被称为国宝。' },
    { id: 'sci005', category: '自然科学与科普', difficulty: '简单', question: '水在多少摄氏度时会结冰？', options: ['0 摄氏度', '100 摄氏度', '25 摄氏度', '50 摄氏度'], answer: '0 摄氏度', explanation: '在标准情况下，水到 0 摄氏度会凝固成冰。' },
    { id: 'sci006', category: '自然科学与科普', difficulty: '简单', question: '彩虹通常说有几种颜色？', options: ['七种', '五种', '十种', '三种'], answer: '七种', explanation: '彩虹常被说成红橙黄绿蓝靛紫七种颜色。' },
    { id: 'sci007', category: '自然科学与科普', difficulty: '简单', question: '下面哪种动物会在冬天冬眠？', options: ['熊', '猫', '狗', '牛'], answer: '熊', explanation: '熊在冬天会冬眠，靠体内储存的脂肪度过寒冬。' },
    { id: 'sci008', category: '自然科学与科普', difficulty: '简单', question: '植物的叶子主要靠什么吸收阳光进行光合作用？', options: ['叶绿素', '根', '茎', '花'], answer: '叶绿素', explanation: '叶子里的叶绿素能吸收阳光，制造养分。' },
    { id: 'sci009', category: '自然科学与科普', difficulty: '简单', question: '人体里负责把血液送到全身的器官是？', options: ['心脏', '肺', '胃', '肝脏'], answer: '心脏', explanation: '心脏像泵一样把血液送到全身各处。' },
    { id: 'sci010', category: '自然科学与科普', difficulty: '简单', question: '为什么白天看不见星星？', options: ['白天阳光太亮遮住了', '星星白天不见了', '星星晚上才出生', '星星白天睡觉了'], answer: '白天阳光太亮遮住了', explanation: '白天阳光太亮，微弱的星光被盖住了。' },
    { id: 'sci011', category: '自然科学与科普', difficulty: '简单', question: '火山喷发时喷出的是？', options: ['岩浆', '清水', '沙子', '雪'], answer: '岩浆', explanation: '火山喷发时喷出炽热的岩浆。' },
    { id: 'sci012', category: '自然科学与科普', difficulty: '简单', question: '下面哪种食物富含维生素 C？', options: ['橙子', '白米饭', '糖块', '食盐'], answer: '橙子', explanation: '橙子等水果富含维生素 C，对身体有益。' },
    { id: 'sci013', category: '自然科学与科普', difficulty: '简单', question: '蜜蜂采蜜时，不知不觉帮花朵做了什么？', options: ['传粉', '浇水', '施肥', '遮光'], answer: '传粉', explanation: '蜜蜂采蜜时把花粉带到其他花上，帮助花朵传粉。' },
    { id: 'sci014', category: '自然科学与科普', difficulty: '简单', question: '一天当中，物体的影子最短的时候大约是？', options: ['正午', '清晨', '傍晚', '深夜'], answer: '正午', explanation: '正午太阳最高，影子最短。' },
    { id: 'sci015', category: '自然科学与科普', difficulty: '简单', question: '磁铁能吸起下面哪种东西？', options: ['铁钉', '塑料尺', '木块', '橡皮'], answer: '铁钉', explanation: '磁铁能吸引铁、钴、镍等金属，铁钉能被吸起。' },
    { id: 'sci016', category: '自然科学与科普', difficulty: '简单', question: '声音是通过什么传到我们耳朵里的？', options: ['空气', '光', '电', '磁铁'], answer: '空气', explanation: '声音靠空气等介质传播，通过空气传进耳朵。' },
    { id: 'sci017', category: '自然科学与科普', difficulty: '简单', question: '下面哪种动物是卵生的？', options: ['鸡', '牛', '马', '羊'], answer: '鸡', explanation: '鸡下蛋孵化，是卵生动物。' },
    { id: 'sci018', category: '自然科学与科普', difficulty: '简单', question: '夏天容易出汗，出汗的主要作用是什么？', options: ['帮助身体散热', '让身体变重', '让皮肤变色', '帮助消化'], answer: '帮助身体散热', explanation: '汗水蒸发会带走热量，帮助身体降温。' },
    { id: 'sci019', category: '自然科学与科普', difficulty: '简单', question: '树木靠什么把水从根部送到叶子？', options: ['茎（树干里的导管）', '根须', '花蕊', '果实'], answer: '茎（树干里的导管）', explanation: '茎里的导管能把根吸收的水分输送到叶子。' },
    { id: 'sci020', category: '自然科学与科普', difficulty: '简单', question: '哪个星球被称为"红色星球"？', options: ['火星', '金星', '水星', '木星'], answer: '火星', explanation: '火星表面含氧化铁而呈红色，被称为红色星球。' },
    { id: 'sci021', category: '自然科学与科普', difficulty: '简单', question: '水的三种状态是？', options: ['固态、液态、气态', '酸、甜、苦', '冷、热、温', '大、中、小'], answer: '固态、液态、气态', explanation: '水可以是冰、液态水和水蒸气三种状态。' },
    { id: 'sci022', category: '自然科学与科普', difficulty: '简单', question: '下面哪种动物会吐丝结网？', options: ['蜘蛛', '蜜蜂', '蚂蚁', '蝴蝶'], answer: '蜘蛛', explanation: '蜘蛛腹部能分泌丝，用来结网捕食。' },
    { id: 'sci023', category: '自然科学与科普', difficulty: '中等', question: '光在下面哪种情况下传播最快？', options: ['真空中', '水中', '玻璃中', '空气中'], answer: '真空中', explanation: '光在真空中速度最快，在介质中会变慢。' },
    { id: 'sci024', category: '自然科学与科普', difficulty: '中等', question: '声音在下面哪种介质中传播最快？', options: ['钢铁', '空气', '水', '真空'], answer: '钢铁', explanation: '声音在固体中传播最快，钢铁比空气和水都快。' },
    { id: 'sci025', category: '自然科学与科普', difficulty: '中等', question: '海洋的潮汐主要是由什么引起的？', options: ['月球的引力', '地球的磁场', '大气压力', '火山活动'], answer: '月球的引力', explanation: '海水涨落主要由月球引力引起，太阳也有影响。' },
    { id: 'sci026', category: '自然科学与科普', difficulty: '中等', question: '植物光合作用时释放出的气体是？', options: ['氧气', '二氧化碳', '氮气', '氢气'], answer: '氧气', explanation: '光合作用吸收二氧化碳，释放出氧气。' },
    { id: 'sci027', category: '自然科学与科普', difficulty: '中等', question: '植物的根主要从土壤中吸收什么？', options: ['水分和无机盐', '阳光和热', '氧气和糖', '石头和沙'], answer: '水分和无机盐', explanation: '根从土壤吸收水分和无机盐，供植物生长。' },
    { id: 'sci028', category: '自然科学与科普', difficulty: '中等', question: '下面哪种动物是哺乳动物？', options: ['鲸', '青蛙', '蛇', '鲤鱼'], answer: '鲸', explanation: '鲸用乳汁喂养幼崽，是生活在海里的哺乳动物。' },
    { id: 'sci029', category: '自然科学与科普', difficulty: '中等', question: '地球自转一圈大约需要多长时间？', options: ['一天（约 24 小时）', '一个月', '一年', '一小时'], answer: '一天（约 24 小时）', explanation: '地球自转一圈约 24 小时，即一天。' },
    { id: 'sci030', category: '自然科学与科普', difficulty: '中等', question: '地球围绕太阳公转一圈大约需要多长时间？', options: ['一年（约 365 天）', '一天', '一个月', '十年'], answer: '一年（约 365 天）', explanation: '地球公转一圈约 365 天，即一年。' },
    { id: 'sci031', category: '自然科学与科普', difficulty: '中等', question: '传统的白炽灯发光主要是靠什么？', options: ['电流通过灯丝发热发光', '摩擦生热', '磁铁吸引', '水蒸气'], answer: '电流通过灯丝发热发光', explanation: '电流通过钨丝使其发热到白炽状态而发光。' },
    { id: 'sci032', category: '自然科学与科普', difficulty: '中等', question: '冬天呼出的气会变成"白雾"，这是为什么？', options: ['呼出的热气遇冷凝结成小水珠', '呼出的是烟', '空气变白了', '肺部变色了'], answer: '呼出的热气遇冷凝结成小水珠', explanation: '呼出的热空气遇到冷空气，水蒸气凝结成小水珠成白雾。' },
    { id: 'sci033', category: '自然科学与科普', difficulty: '中等', question: '放大镜属于哪种透镜？', options: ['凸透镜', '凹透镜', '平面镜', '三棱镜'], answer: '凸透镜', explanation: '放大镜是中间厚边缘薄的凸透镜，能把物体放大。' },
    { id: 'sci034', category: '自然科学与科普', difficulty: '中等', question: '潜望镜主要利用了什么原理？', options: ['平面镜反射', '凸透镜折射', '凹透镜折射', '透镜聚焦'], answer: '平面镜反射', explanation: '潜望镜用两面平面镜反射光线，实现拐弯观察。' },
    { id: 'sci035', category: '自然科学与科普', difficulty: '中等', question: '下面哪种液体通常会浮在水面上？', options: ['油', '浓盐水', '蜂蜜', '水银'], answer: '油', explanation: '油比水轻，所以会浮在水面上。' },
    { id: 'sci036', category: '自然科学与科普', difficulty: '中等', question: '蝙蝠在黑暗里主要靠什么判断方向？', options: ['回声定位', '眼睛发光', '鼻子嗅觉', '触角'], answer: '回声定位', explanation: '蝙蝠发出声波，靠回声判断障碍物和猎物位置。' },
    { id: 'sci037', category: '自然科学与科普', difficulty: '中等', question: '铁在潮湿的环境里容易发生什么变化？', options: ['生锈', '熔化', '发光', '变透明'], answer: '生锈', explanation: '铁在潮湿有氧的环境下容易生锈。' },
    { id: 'sci038', category: '自然科学与科普', difficulty: '中等', question: '空气中哪种气体是植物进行光合作用所需要的？', options: ['二氧化碳', '氧气', '氮气', '氢气'], answer: '二氧化碳', explanation: '植物光合作用吸收空气中的二氧化碳。' },
    { id: 'sci039', category: '自然科学与科普', difficulty: '中等', question: '点燃蜡烛时，蜡烛油（石蜡）先发生什么变化？', options: ['先熔化再燃烧', '直接变气体不燃烧', '变成水', '变成铁'], answer: '先熔化再燃烧', explanation: '蜡烛受热先熔化成液体，再受热蒸发并被点燃。' },
    { id: 'sci040', category: '自然科学与科普', difficulty: '中等', question: '吹电风扇感觉凉快，主要是因为什么？', options: ['加快皮肤表面汗液蒸发', '吹来了冷气', '风本身很冷', '风扇降低了空气温度'], answer: '加快皮肤表面汗液蒸发', explanation: '风吹加快汗液蒸发，蒸发带走热量让人感觉凉快。' },
    { id: 'sci041', category: '自然科学与科普', difficulty: '中等', question: '地球表面被海洋覆盖的面积大约占多少？', options: ['约七成', '约三成', '约一半', '约九成'], answer: '约七成', explanation: '海洋约占地球表面的七成，陆地约占三成。' },
    { id: 'sci042', category: '自然科学与科普', difficulty: '中等', question: '月亮绕地球转一圈（一个农历月）大约需要？', options: ['约 29 天', '约一天', '约一年', '约一周'], answer: '约 29 天', explanation: '一个朔望月约 29.5 天，通常说一个月左右。' },
    { id: 'sci043', category: '自然科学与科普', difficulty: '困难', question: '放大镜能把物体放大，主要原因是？', options: ['凸透镜折射光线会聚成像', '凹透镜发散光线', '平面镜反射', '镜片颜色变深'], answer: '凸透镜折射光线会聚成像', explanation: '凸透镜折射光使光线会聚，形成放大的像。' },
    { id: 'sci044', category: '自然科学与科普', difficulty: '困难', question: '在一个标准大气压下，水的沸点是？', options: ['100 摄氏度', '0 摄氏度', '50 摄氏度', '200 摄氏度'], answer: '100 摄氏度', explanation: '标准大气压下，水加热到 100 摄氏度沸腾。' },
    { id: 'sci045', category: '自然科学与科普', difficulty: '困难', question: '为什么深海鱼能生活在巨大的水压下？', options: ['它们体内外压力平衡，适应了高压', '它们不怕压', '它们有坚硬盔甲', '它们会游泳'], answer: '它们体内外压力平衡，适应了高压', explanation: '深海鱼体内外压力平衡，所以能承受深海高压。' },
    { id: 'sci046', category: '自然科学与科普', difficulty: '困难', question: '"光年"是用来表示什么的单位？', options: ['距离', '时间', '速度', '温度'], answer: '距离', explanation: '光年指光一年走的距离，是天文上的长度单位。' },
    { id: 'sci047', category: '自然科学与科普', difficulty: '困难', question: '地球内部的圈层从外到内依次是？', options: ['地壳、地幔、地核', '地核、地幔、地壳', '地幔、地壳、地核', '地壳、地核、地幔'], answer: '地壳、地幔、地核', explanation: '从外到内是地壳、地幔、地核三层。' },
    { id: 'sci048', category: '自然科学与科普', difficulty: '困难', question: '把一块磁铁从中间折断成两段，两段会怎样？', options: ['都仍然有南北极', '都失去磁性', '只有一段有磁性', '变成普通铁'], answer: '都仍然有南北极', explanation: '磁铁折断后每段都仍带有南北极，磁性不会消失。' },
    { id: 'sci049', category: '自然科学与科普', difficulty: '困难', question: '彩虹从外到内的颜色顺序是？', options: ['红、橙、黄、绿、蓝、靛、紫', '紫、靛、蓝、绿、黄、橙、红', '红、绿、蓝、黄、紫、靛、橙', '蓝、紫、红、橙、绿、黄、靛'], answer: '红、橙、黄、绿、蓝、靛、紫', explanation: '彩虹从外向内是红橙黄绿蓝靛紫七色。' },
    { id: 'sci050', category: '自然科学与科普', difficulty: '困难', question: '人体最大的器官是？', options: ['皮肤', '心脏', '肝脏', '大脑'], answer: '皮肤', explanation: '皮肤覆盖全身，是人体面积最大的器官。' },
    { id: 'sci051', category: '自然科学与科普', difficulty: '困难', question: '夏天穿浅色衣服更凉快，主要原因是？', options: ['浅色反射阳光，吸收热量少', '浅色自己会制冷', '浅色布料更薄', '浅色不透气'], answer: '浅色反射阳光，吸收热量少', explanation: '浅色反射阳光、吸热少，所以感觉更凉快。' },
    { id: 'sci052', category: '自然科学与科普', difficulty: '困难', question: '蜡烛吹灭后冒出的"白烟"主要是？', options: ['石蜡蒸气遇冷凝结的小颗粒', '纯水', '铁粉', '灰尘'], answer: '石蜡蒸气遇冷凝结的小颗粒', explanation: '白烟是石蜡蒸气遇冷凝结成的极小颗粒。' },
    { id: 'sci053', category: '自然科学与科普', difficulty: '困难', question: '在月球上，因为没有空气，宇航员面对面说话会怎样？', options: ['听不清，需靠无线电通话', '和地球上一样清楚', '声音更大', '声音会反弹'], answer: '听不清，需靠无线电通话', explanation: '声音靠空气传播，月球没有空气所以听不见，要靠无线电。' },
    { id: 'sci054', category: '自然科学与科普', difficulty: '困难', question: '把筷子斜着插进水里，看起来会怎样？', options: ['弯折，是光的折射', '变直，是光的反射', '变短，是影子', '没有变化'], answer: '弯折，是光的折射', explanation: '光从水进入空气时方向改变，筷子看起来弯折，这是折射。' },
    { id: 'sci055', category: '自然科学与科普', difficulty: '困难', question: '天上的云是由什么组成的？', options: ['小水滴和小冰晶', '棉花', '白色油漆', '羊毛'], answer: '小水滴和小冰晶', explanation: '云是大量小水滴和小冰晶聚集形成的。' },
    { id: 'sci056', category: '自然科学与科普', difficulty: '困难', question: '地球获得热量的主要来源是？', options: ['太阳辐射', '地核的热量', '月亮反射', '星星'], answer: '太阳辐射', explanation: '地球热量主要来自太阳的辐射。' },
    { id: 'sci057', category: '自然科学与科普', difficulty: '困难', question: '指南针的指针为什么总是指向北方？', options: ['地球本身有磁场', '指针对北方敏感', '磁铁放在北极', '星星指引'], answer: '地球本身有磁场', explanation: '地球是个大磁体，指南针受地磁场作用指向南北。' },
    { id: 'sci058', category: '自然科学与科普', difficulty: '困难', question: '为什么云朵看起来是白色的？', options: ['云中的水滴反射阳光', '云本身是白色物质', '云上有雪', '云的化学成分'], answer: '云中的水滴反射阳光', explanation: '云中水滴把阳光散射反射，看起来就是白色。' },
    { id: 'sci059', category: '自然科学与科普', difficulty: '困难', question: '热气球能升上天空，是利用了什么原理？', options: ['热空气比冷空气轻', '冷空气比热空气轻', '气球里装了氢气', '靠风力吹上去'], answer: '热空气比冷空气轻', explanation: '加热使球内空气变轻，浮力大于重力就能上升。' },
    { id: 'sci060', category: '自然科学与科普', difficulty: '困难', question: '把一块冰放进水里，冰块会怎样？', options: ['浮在水面上', '沉到水底', '立即融化消失', '变成水蒸气'], answer: '浮在水面上', explanation: '冰的密度比水小，所以冰块浮在水面上。' },
    /* ================= 语文与古诗 45 ================= */
    { id: 'chi001', category: '语文与古诗', difficulty: '简单', question: '"床前明月光"的下一句是？', options: ['疑是地上霜', '低头思故乡', '举头望明月', '白日依山尽'], answer: '疑是地上霜', explanation: '《静夜思》：\"床前明月光，疑是地上霜。\"' },
    { id: 'chi002', category: '语文与古诗', difficulty: '简单', question: '"白日依山尽"的下一句是？', options: ['黄河入海流', '更上一层楼', '春风吹又生', '处处闻啼鸟'], answer: '黄河入海流', explanation: '《登鹳雀楼》：\"白日依山尽，黄河入海流。\"' },
    { id: 'chi003', category: '语文与古诗', difficulty: '简单', question: '"春眠不觉晓"的下一句是？', options: ['处处闻啼鸟', '花落知多少', '夜来风雨声', '低头思故乡'], answer: '处处闻啼鸟', explanation: '《春晓》：\"春眠不觉晓，处处闻啼鸟。\"' },
    { id: 'chi004', category: '语文与古诗', difficulty: '简单', question: '"锄禾日当午"的下一句是？', options: ['汗滴禾下土', '粒粒皆辛苦', '谁知盘中餐', '春种一粒粟'], answer: '汗滴禾下土', explanation: '《悯农》：\"锄禾日当午，汗滴禾下土。\"' },
    { id: 'chi005', category: '语文与古诗', difficulty: '简单', question: '"举头望明月"的下一句是？', options: ['低头思故乡', '疑是地上霜', '明月几时有', '海内存知己'], answer: '低头思故乡', explanation: '《静夜思》：\"举头望明月，低头思故乡。\"' },
    { id: 'chi006', category: '语文与古诗', difficulty: '简单', question: '"谁知盘中餐"的下一句是？', options: ['粒粒皆辛苦', '汗滴禾下土', '春种一粒粟', '万紫千红总是春'], answer: '粒粒皆辛苦', explanation: '《悯农》：\"谁知盘中餐，粒粒皆辛苦。\"' },
    { id: 'chi007', category: '语文与古诗', difficulty: '简单', question: '古诗《咏鹅》"鹅鹅鹅"的作者是？', options: ['骆宾王', '李白', '杜甫', '白居易'], answer: '骆宾王', explanation: '《咏鹅》相传是骆宾王七岁时所作。' },
    { id: 'chi008', category: '语文与古诗', difficulty: '简单', question: '"野火烧不尽"的下一句是？', options: ['春风吹又生', '更上一层楼', '处处闻啼鸟', '低头思故乡'], answer: '春风吹又生', explanation: '白居易《赋得古原草送别》：\"野火烧不尽，春风吹又生。\"' },
    { id: 'chi009', category: '语文与古诗', difficulty: '简单', question: '"两个黄鹂鸣翠柳"的作者是？', options: ['杜甫', '李白', '王维', '孟浩然'], answer: '杜甫', explanation: '这是杜甫《绝句》中的名句。' },
    { id: 'chi010', category: '语文与古诗', difficulty: '简单', question: '"欲穷千里目"的下一句是？', options: ['更上一层楼', '黄河入海流', '春风吹又生', '白日依山尽'], answer: '更上一层楼', explanation: '《登鹳雀楼》：\"欲穷千里目，更上一层楼。\"' },
    { id: 'chi011', category: '语文与古诗', difficulty: '简单', question: '"小荷才露尖尖角"的下一句是？', options: ['早有蜻蜓立上头', '映日荷花别样红', '接天莲叶无穷碧', '万紫千红总是春'], answer: '早有蜻蜓立上头', explanation: '杨万里《小池》：\"小荷才露尖尖角，早有蜻蜓立上头。\"' },
    { id: 'chi012', category: '语文与古诗', difficulty: '简单', question: '古诗《静夜思》的作者是？', options: ['李白', '杜甫', '白居易', '王维'], answer: '李白', explanation: '《静夜思》是唐代诗人李白的名作。' },
    { id: 'chi013', category: '语文与古诗', difficulty: '简单', question: '成语"画蛇添足"比喻什么？', options: ['多此一举', '画得好看', '手脚麻利', '做事踏实'], answer: '多此一举', explanation: '"画蛇添足"指做了多余的事，多此一举。' },
    { id: 'chi014', category: '语文与古诗', difficulty: '简单', question: '成语"亡羊补牢"的意思接近下面哪个？', options: ['出了问题后及时补救', '羊丢了不管', '提前预防一切', '做事鲁莽'], answer: '出了问题后及时补救', explanation: '"亡羊补牢"指出了差错后及时补救还不算晚。' },
    { id: 'chi015', category: '语文与古诗', difficulty: '简单', question: '汉字"日"共有几画？', options: ['4 画', '3 画', '5 画', '2 画'], answer: '4 画', explanation: '"日"字共四画：竖、横折、横、横。' },
    { id: 'chi016', category: '语文与古诗', difficulty: '简单', question: '"花落知多少"出自哪首诗？', options: ['《春晓》', '《静夜思》', '《登鹳雀楼》', '《咏鹅》'], answer: '《春晓》', explanation: '孟浩然《春晓》：\"夜来风雨声，花落知多少。\"' },
    { id: 'chi017', category: '语文与古诗', difficulty: '简单', question: '汉字"山"共有几画？', options: ['3 画', '4 画', '2 画', '5 画'], answer: '3 画', explanation: '"山"字共三画：竖、竖折、竖。' },
    { id: 'chi018', category: '语文与古诗', difficulty: '中等', question: '古诗"停车坐爱枫林晚"中的"坐"是什么意思？', options: ['因为', '坐下', '乘坐', '座位'], answer: '因为', explanation: '这里的"坐"是"因为"的意思，指因为喜爱枫林晚景而停车。' },
    { id: 'chi019', category: '语文与古诗', difficulty: '中等', question: '"欲穷千里目"中的"穷"是什么意思？', options: ['尽、看完', '贫穷', '穷尽力气', '穷苦'], answer: '尽、看完', explanation: '这里的"穷"是"尽"的意思，指看遍千里景色。' },
    { id: 'chi020', category: '语文与古诗', difficulty: '中等', question: '成语"守株待兔"告诉我们要？', options: ['不能心存侥幸，要脚踏实地', '天天等在树下', '要多种树', '要跑得快'], answer: '不能心存侥幸，要脚踏实地', explanation: '"守株待兔"讽刺不劳而获、心存侥幸，告诫要脚踏实地。' },
    { id: 'chi021', category: '语文与古诗', difficulty: '中等', question: '成语"望梅止渴"的故事主人公是？', options: ['曹操', '刘备', '孙权', '关羽'], answer: '曹操', explanation: '"望梅止渴"讲曹操用梅子让大家嘴里生津止渴的故事。' },
    { id: 'chi022', category: '语文与古诗', difficulty: '中等', question: '成语"掩耳盗铃"比喻什么？', options: ['自己欺骗自己', '耳朵不好使', '偷东西', '害怕铃声'], answer: '自己欺骗自己', explanation: '"掩耳盗铃"指捂住耳朵偷铃，比喻自己欺骗自己。' },
    { id: 'chi023', category: '语文与古诗', difficulty: '中等', question: '古诗《咏柳》"碧玉妆成一树高"的作者是？', options: ['贺知章', '李白', '杜牧', '王昌龄'], answer: '贺知章', explanation: '《咏柳》是唐代诗人贺知章所作。' },
    { id: 'chi024', category: '语文与古诗', difficulty: '中等', question: '"春色满园关不住"的下一句是？', options: ['一枝红杏出墙来', '万紫千红总是春', '春风吹又生', '处处闻啼鸟'], answer: '一枝红杏出墙来', explanation: '叶绍翁《游园不值》：\"春色满园关不住，一枝红杏出墙来。\"' },
    { id: 'chi025', category: '语文与古诗', difficulty: '中等', question: '"不识庐山真面目"的下一句是？', options: ['只缘身在此山中', '远近高低各不同', '飞流直下三千尺', '横看成岭侧成峰'], answer: '只缘身在此山中', explanation: '苏轼《题西林壁》：\"不识庐山真面目，只缘身在此山中。\"' },
    { id: 'chi026', category: '语文与古诗', difficulty: '中等', question: '"飞流直下三千尺"出自哪首诗？', options: ['《望庐山瀑布》', '《静夜思》', '《登鹳雀楼》', '《春晓》'], answer: '《望庐山瀑布》', explanation: '李白《望庐山瀑布》：\"飞流直下三千尺，疑是银河落九天。\"' },
    { id: 'chi027', category: '语文与古诗', difficulty: '中等', question: '成语"亡羊补牢"中的"牢"是什么意思？', options: ['羊圈', '牢房', '牢固', '劳苦'], answer: '羊圈', explanation: '这里的"牢"指羊圈，补牢就是修补羊圈。' },
    { id: 'chi028', category: '语文与古诗', difficulty: '中等', question: '"明月几时有"的作者是？', options: ['苏轼', '李白', '辛弃疾', '王安石'], answer: '苏轼', explanation: '"明月几时有，把酒问青天"出自苏轼《水调歌头》。' },
    { id: 'chi029', category: '语文与古诗', difficulty: '中等', question: '汉字"鸟"共有几画？', options: ['5 画', '4 画', '6 画', '3 画'], answer: '5 画', explanation: '"鸟"字共五画：撇、横折钩、点、竖折折钩、横。' },
    { id: 'chi030', category: '语文与古诗', difficulty: '中等', question: '成语"叶公好龙"比喻什么？', options: ['表面喜欢，实际害怕', '真的很喜欢龙', '做事认真', '见多识广'], answer: '表面喜欢，实际害怕', explanation: '"叶公好龙"讽刺嘴上说喜欢、实际却害怕的人。' },
    { id: 'chi031', category: '语文与古诗', difficulty: '中等', question: '"疑是银河落九天"中的"银河"指的是？', options: ['天上的星河（比喻瀑布）', '地上的一条河', '银做的河', '一条小路'], answer: '天上的星河（比喻瀑布）', explanation: '这里用银河比喻庐山瀑布，夸张而形象。' },
    { id: 'chi032', category: '语文与古诗', difficulty: '中等', question: '古诗《登鹳雀楼》的作者是？', options: ['王之涣', '李白', '杜甫', '白居易'], answer: '王之涣', explanation: '《登鹳雀楼》是唐代诗人王之涣所作。' },
    { id: 'chi033', category: '语文与古诗', difficulty: '困难', question: '"故人西辞黄鹤楼"的下一句是？', options: ['烟花三月下扬州', '孤帆远影碧空尽', '唯见长江天际流', '春风不度玉门关'], answer: '烟花三月下扬州', explanation: '李白《黄鹤楼送孟浩然之广陵》：\"故人西辞黄鹤楼，烟花三月下扬州。\"' },
    { id: 'chi034', category: '语文与古诗', difficulty: '困难', question: '"春风不度玉门关"的上一句是？', options: ['羌笛何须怨杨柳', '黄河远上白云间', '一片孤城万仞山', '欲穷千里目'], answer: '羌笛何须怨杨柳', explanation: '王之涣《凉州词》：\"羌笛何须怨杨柳，春风不度玉门关。\"' },
    { id: 'chi035', category: '语文与古诗', difficulty: '困难', question: '"会当凌绝顶"的下一句是？', options: ['一览众山小', '决眦入归鸟', '荡胸生曾云', '齐鲁青未了'], answer: '一览众山小', explanation: '杜甫《望岳》：\"会当凌绝顶，一览众山小。\"' },
    { id: 'chi036', category: '语文与古诗', difficulty: '困难', question: '"无边落木萧萧下"的下一句是？', options: ['不尽长江滚滚来', '万里悲秋常作客', '百年多病独登台', '风急天高猿啸哀'], answer: '不尽长江滚滚来', explanation: '杜甫《登高》：\"无边落木萧萧下，不尽长江滚滚来。\"' },
    { id: 'chi037', category: '语文与古诗', difficulty: '困难', question: '成语"滥竽充数"故事中的主人公是？', options: ['南郭先生', '东郭先生', '叶公', '塞翁'], answer: '南郭先生', explanation: '"滥竽充数"讲南郭先生不会吹竽却混在队伍里充数。' },
    { id: 'chi038', category: '语文与古诗', difficulty: '困难', question: '"大漠孤烟直"的下一句是？', options: ['长河落日圆', '归雁入胡天', '征蓬出汉塞', '萧关逢候骑'], answer: '长河落日圆', explanation: '王维《使至塞上》：\"大漠孤烟直，长河落日圆。\"' },
    { id: 'chi039', category: '语文与古诗', difficulty: '困难', question: '"千门万户曈曈日"的下一句是？', options: ['总把新桃换旧符', '春风送暖入屠苏', '爆竹声中一岁除', '遥知兄弟登高处'], answer: '总把新桃换旧符', explanation: '王安石《元日》：\"千门万户曈曈日，总把新桃换旧符。\"' },
    { id: 'chi040', category: '语文与古诗', difficulty: '困难', question: '"横看成岭侧成峰"的下一句是？', options: ['远近高低各不同', '只缘身在此山中', '不识庐山真面目', '飞流直下三千尺'], answer: '远近高低各不同', explanation: '苏轼《题西林壁》：\"横看成岭侧成峰，远近高低各不同。\"' },
    { id: 'chi041', category: '语文与古诗', difficulty: '困难', question: '"落红不是无情物"的下一句是？', options: ['化作春泥更护花', '春风吹又生', '映日荷花别样红', '万紫千红总是春'], answer: '化作春泥更护花', explanation: '龚自珍《己亥杂诗》：\"落红不是无情物，化作春泥更护花。\"' },
    { id: 'chi042', category: '语文与古诗', difficulty: '困难', question: '"商女不知亡国恨"的下一句是？', options: ['隔江犹唱后庭花', '烟笼寒水月笼沙', '夜泊秦淮近酒家', '白云深处有人家'], answer: '隔江犹唱后庭花', explanation: '杜牧《泊秦淮》：\"商女不知亡国恨，隔江犹唱后庭花。\"' },
    { id: 'chi043', category: '语文与古诗', difficulty: '困难', question: '成语"邯郸学步"比喻什么？', options: ['盲目模仿别人，反而失去自己的本领', '走路很快', '学走路很认真', '见多识广'], answer: '盲目模仿别人，反而失去自己的本领', explanation: '"邯郸学步"比喻一味模仿别人，反而丢了自己的长处。' },
    { id: 'chi044', category: '语文与古诗', difficulty: '困难', question: '"问渠那得清如许"的下一句是？', options: ['为有源头活水来', '半亩方塘一鉴开', '天光云影共徘徊', '一水护田将绿绕'], answer: '为有源头活水来', explanation: '朱熹《观书有感》：\"问渠那得清如许，为有源头活水来。\"' },
    { id: 'chi045', category: '语文与古诗', difficulty: '困难', question: '成语"胸有成竹"比喻什么？', options: ['做事前已有充分把握', '胸里有竹子', '身体很健康', '见多识广'], answer: '做事前已有充分把握', explanation: '"胸有成竹"指画竹前心中已有竹的样子，比喻做事前有把握。' },
    /* ================= 数学思维与基础奥数 40 ================= */
    { id: 'math001', category: '数学思维与基础奥数', difficulty: '简单', question: '8 + 7 等于多少？', options: ['15', '14', '16', '13'], answer: '15', explanation: '8 + 7 = 15。' },
    { id: 'math002', category: '数学思维与基础奥数', difficulty: '简单', question: '15 - 9 等于多少？', options: ['6', '5', '7', '4'], answer: '6', explanation: '15 - 9 = 6。' },
    { id: 'math003', category: '数学思维与基础奥数', difficulty: '简单', question: '3 × 4 等于多少？', options: ['12', '7', '14', '9'], answer: '12', explanation: '3 × 4 = 12。' },
    { id: 'math004', category: '数学思维与基础奥数', difficulty: '简单', question: '18 ÷ 6 等于多少？', options: ['3', '4', '2', '6'], answer: '3', explanation: '18 ÷ 6 = 3。' },
    { id: 'math005', category: '数学思维与基础奥数', difficulty: '简单', question: '最小的两位数是？', options: ['10', '11', '99', '0'], answer: '10', explanation: '最小的两位数是 10。' },
    { id: 'math006', category: '数学思维与基础奥数', difficulty: '简单', question: '比 20 大 5 的数是？', options: ['25', '15', '30', '20'], answer: '25', explanation: '20 + 5 = 25。' },
    { id: 'math007', category: '数学思维与基础奥数', difficulty: '简单', question: '一个三角形有几条边？', options: ['3 条', '4 条', '2 条', '5 条'], answer: '3 条', explanation: '三角形有三条边、三个角。' },
    { id: 'math008', category: '数学思维与基础奥数', difficulty: '简单', question: '一个正方形有几条边？', options: ['4 条', '3 条', '5 条', '6 条'], answer: '4 条', explanation: '正方形有四条相等且互相垂直的边。' },
    { id: 'math009', category: '数学思维与基础奥数', difficulty: '简单', question: '7 + 7 + 7 等于多少？', options: ['21', '14', '24', '18'], answer: '21', explanation: '7 × 3 = 21。' },
    { id: 'math010', category: '数学思维与基础奥数', difficulty: '简单', question: '与 30 相邻的两个数是？', options: ['29 和 31', '28 和 32', '20 和 40', '30 和 31'], answer: '29 和 31', explanation: '30 前一个是 29，后一个是 31。' },
    { id: 'math011', category: '数学思维与基础奥数', difficulty: '简单', question: '从 1 数到 10，一共有几个数？', options: ['10 个', '9 个', '11 个', '5 个'], answer: '10 个', explanation: '1 到 10 一共是 10 个数。' },
    { id: 'math012', category: '数学思维与基础奥数', difficulty: '简单', question: '5 个 10 相加是多少？', options: ['50', '15', '55', '5'], answer: '50', explanation: '5 × 10 = 50。' },
    { id: 'math013', category: '数学思维与基础奥数', difficulty: '简单', question: '一天有 24 小时，那么半天是几小时？', options: ['12 小时', '6 小时', '24 小时', '8 小时'], answer: '12 小时', explanation: '24 ÷ 2 = 12 小时。' },
    { id: 'math014', category: '数学思维与基础奥数', difficulty: '简单', question: '把 10 个苹果平均分给 5 个小朋友，每人分几个？', options: ['2 个', '5 个', '3 个', '10 个'], answer: '2 个', explanation: '10 ÷ 5 = 2 个。' },
    { id: 'math015', category: '数学思维与基础奥数', difficulty: '中等', question: '找规律：2, 4, 6, 8, （  ）？', options: ['10', '9', '12', '7'], answer: '10', explanation: '每次加 2，所以 8 后面是 10。' },
    { id: 'math016', category: '数学思维与基础奥数', difficulty: '中等', question: '找规律：1, 3, 5, 7, （  ）？', options: ['9', '8', '11', '6'], answer: '9', explanation: '每次加 2，7 后面是 9。' },
    { id: 'math017', category: '数学思维与基础奥数', difficulty: '中等', question: '找规律：3, 6, 9, 12, （  ）？', options: ['15', '13', '18', '14'], answer: '15', explanation: '每次加 3，12 后面是 15。' },
    { id: 'math018', category: '数学思维与基础奥数', difficulty: '中等', question: '一盒铅笔有 12 支，用掉 4 支后还剩几支？', options: ['8 支', '16 支', '7 支', '9 支'], answer: '8 支', explanation: '12 - 4 = 8 支。' },
    { id: 'math019', category: '数学思维与基础奥数', difficulty: '中等', question: '3 + 4 + 7 等于多少？', options: ['14', '13', '15', '11'], answer: '14', explanation: '3 + 4 + 7 = 14。' },
    { id: 'math020', category: '数学思维与基础奥数', difficulty: '中等', question: '找规律：5, 10, 15, 20, （  ）？', options: ['25', '22', '30', '24'], answer: '25', explanation: '每次加 5，20 后面是 25。' },
    { id: 'math021', category: '数学思维与基础奥数', difficulty: '中等', question: '两个数的和是 20，其中一个数是 8，另一个数是几？', options: ['12', '14', '10', '15'], answer: '12', explanation: '20 - 8 = 12。' },
    { id: 'math022', category: '数学思维与基础奥数', difficulty: '中等', question: '9 × 6 等于多少？', options: ['54', '45', '63', '36'], answer: '54', explanation: '9 × 6 = 54。' },
    { id: 'math023', category: '数学思维与基础奥数', difficulty: '中等', question: '一个苹果 3 元，买 5 个要多少钱？', options: ['15 元', '8 元', '12 元', '18 元'], answer: '15 元', explanation: '3 × 5 = 15 元。' },
    { id: 'math024', category: '数学思维与基础奥数', difficulty: '中等', question: '8 的一半是多少？', options: ['4', '3', '5', '6'], answer: '4', explanation: '8 ÷ 2 = 4。' },
    { id: 'math025', category: '数学思维与基础奥数', difficulty: '中等', question: '100 以内最大的两位数是？', options: ['99', '98', '100', '90'], answer: '99', explanation: '最大的两位数是 99。' },
    { id: 'math026', category: '数学思维与基础奥数', difficulty: '中等', question: '6 × 8 等于多少？', options: ['48', '42', '54', '56'], answer: '48', explanation: '6 × 8 = 48。' },
    { id: 'math027', category: '数学思维与基础奥数', difficulty: '中等', question: '48 ÷ 8 等于多少？', options: ['6', '7', '5', '8'], answer: '6', explanation: '48 ÷ 8 = 6。' },
    { id: 'math028', category: '数学思维与基础奥数', difficulty: '困难', question: '找规律：1, 4, 7, 10, （  ）？', options: ['13', '12', '14', '11'], answer: '13', explanation: '每次加 3，10 后面是 13。' },
    { id: 'math029', category: '数学思维与基础奥数', difficulty: '困难', question: '11 + 22 + 33 等于多少？', options: ['66', '55', '77', '60'], answer: '66', explanation: '11 + 22 + 33 = 66。' },
    { id: 'math030', category: '数学思维与基础奥数', difficulty: '困难', question: '找规律：2, 4, 8, 16, （  ）？', options: ['32', '24', '20', '18'], answer: '32', explanation: '每次乘 2，16 后面是 32。' },
    { id: 'math031', category: '数学思维与基础奥数', difficulty: '困难', question: '有 14 个橘子，每 2 个装一袋，能装几袋？', options: ['7 袋', '6 袋', '8 袋', '5 袋'], answer: '7 袋', explanation: '14 ÷ 2 = 7 袋。' },
    { id: 'math032', category: '数学思维与基础奥数', difficulty: '困难', question: '一个两位数，十位是 5，个位是 3，这个数是？', options: ['53', '35', '8', '58'], answer: '53', explanation: '十位是 5 表示 50，个位 3，合起来是 53。' },
    { id: 'math033', category: '数学思维与基础奥数', difficulty: '困难', question: '找规律：3, 6, 12, 24, （  ）？', options: ['48', '36', '30', '42'], answer: '48', explanation: '每次乘 2，24 后面是 48。' },
    { id: 'math034', category: '数学思维与基础奥数', difficulty: '困难', question: '25 里面有几个 5？', options: ['5 个', '4 个', '6 个', '3 个'], answer: '5 个', explanation: '25 ÷ 5 = 5 个。' },
    { id: 'math035', category: '数学思维与基础奥数', difficulty: '困难', question: '把 36 平均分成 6 份，每份是多少？', options: ['6', '5', '7', '4'], answer: '6', explanation: '36 ÷ 6 = 6。' },
    { id: 'math036', category: '数学思维与基础奥数', difficulty: '困难', question: '6 个同学围成一圈，每人只和左右相邻的同学握一次手，一共握手几次？', options: ['6 次', '5 次', '10 次', '12 次'], answer: '6 次', explanation: '围成一圈有 6 对相邻同学，每对只握一次，所以共 6 次。' },
    { id: 'math037', category: '数学思维与基础奥数', difficulty: '困难', question: '找规律：5, 9, 13, 17, （  ）？', options: ['21', '20', '19', '18'], answer: '21', explanation: '每次加 4，17 后面是 21。' },
    { id: 'math038', category: '数学思维与基础奥数', difficulty: '困难', question: '一袋糖每 5 颗分一组，最后还剩 2 颗。下面哪一个可能是糖的总数？', options: ['27 颗', '25 颗', '30 颗', '35 颗'], answer: '27 颗', explanation: '27 除以 5 余 2，其他三个数都能被 5 整除。' },
    { id: 'math039', category: '数学思维与基础奥数', difficulty: '困难', question: '找规律：10, 8, 6, 4, （  ）？', options: ['2', '3', '5', '0'], answer: '2', explanation: '每次减 2，4 后面是 2。' },
    { id: 'math040', category: '数学思维与基础奥数', difficulty: '困难', question: '1 + 2 + 3 + 4 + 5 等于多少？', options: ['15', '14', '16', '13'], answer: '15', explanation: '1 + 2 + 3 + 4 + 5 = 15。' },
    /* ================= 历史与地理 40 ================= */
    { id: 'geo001', category: '历史与地理', difficulty: '简单', question: '我国的国旗是？', options: ['五星红旗', '太阳旗', '星条旗', '米字旗'], answer: '五星红旗', explanation: '我国的国旗是五星红旗，旗面为红色。' },
    { id: 'geo002', category: '历史与地理', difficulty: '简单', question: '我国的首都是？', options: ['北京', '上海', '广州', '西安'], answer: '北京', explanation: '北京是中华人民共和国的首都。' },
    { id: 'geo003', category: '历史与地理', difficulty: '简单', question: '我国的首都北京属于哪个大洲？', options: ['亚洲', '欧洲', '非洲', '南美洲'], answer: '亚洲', explanation: '中国位于亚洲，北京是我国的首都。' },
    { id: 'geo004', category: '历史与地理', difficulty: '简单', question: '下面哪条河流被称为我国的"母亲河"？', options: ['黄河', '长江', '珠江', '黑龙江'], answer: '黄河', explanation: '黄河是中华民族的母亲河，孕育了中华文明。' },
    { id: 'geo005', category: '历史与地理', difficulty: '简单', question: '我国最长的河流是？', options: ['长江', '黄河', '淮河', '珠江'], answer: '长江', explanation: '长江是我国流程最长、流域最广的河流。' },
    { id: 'geo006', category: '历史与地理', difficulty: '简单', question: '我国的国宝动物大熊猫主要生活在哪里？', options: ['四川等地', '沙漠', '海边', '北极'], answer: '四川等地', explanation: '大熊猫主要生活在四川、陕西、甘肃等地的山林。' },
    { id: 'geo007', category: '历史与地理', difficulty: '简单', question: '一天中有多少个小时？', options: ['24 小时', '12 小时', '10 小时', '48 小时'], answer: '24 小时', explanation: '一天是 24 小时。' },
    { id: 'geo008', category: '历史与地理', difficulty: '简单', question: '一年有几个季节？', options: ['四个', '两个', '三个', '五个'], answer: '四个', explanation: '一年有春、夏、秋、冬四个季节。' },
    { id: 'geo009', category: '历史与地理', difficulty: '简单', question: '我国国庆节是几月几日？', options: ['10 月 1 日', '1 月 1 日', '5 月 1 日', '6 月 1 日'], answer: '10 月 1 日', explanation: '每年的 10 月 1 日是我国的国庆节。' },
    { id: 'geo010', category: '历史与地理', difficulty: '简单', question: '世界上海拔最高的山峰是？', options: ['珠穆朗玛峰', '泰山', '黄山', '华山'], answer: '珠穆朗玛峰', explanation: '珠穆朗玛峰是世界上海拔最高的山峰。' },
    { id: 'geo011', category: '历史与地理', difficulty: '简单', question: '地球上有几个大洲？', options: ['七个', '五个', '六个', '四个'], answer: '七个', explanation: '地球有七大洲：亚、欧、非、北美、南美、大洋洲、南极洲。' },
    { id: 'geo012', category: '历史与地理', difficulty: '简单', question: '我国的首都有多座著名的古代皇宫建筑，其中最著名的是？', options: ['故宫', '长城', '天坛', '颐和园'], answer: '故宫', explanation: '故宫是明清两代的皇宫，位于北京，是世界上现存最大的宫殿建筑群。' },
    { id: 'geo013', category: '历史与地理', difficulty: '简单', question: '世界上最广阔的海洋是？', options: ['太平洋', '大西洋', '印度洋', '北冰洋'], answer: '太平洋', explanation: '太平洋是世界上面积最大、最深的海洋。' },
    { id: 'geo014', category: '历史与地理', difficulty: '简单', question: '太阳系中离太阳最近的行星是？', options: ['水星', '金星', '地球', '火星'], answer: '水星', explanation: '水星离太阳最近，绕太阳一圈只需约 88 天。' },
    { id: 'geo015', category: '历史与地理', difficulty: '中等', question: '我国一共有多少个省级行政区（含省、自治区、直辖市和特别行政区）？', options: ['34 个', '30 个', '36 个', '40 个'], answer: '34 个', explanation: '我国共有 34 个省级行政区。' },
    { id: 'geo016', category: '历史与地理', difficulty: '中等', question: '我国的首都北京位于华北平原的什么位置？', options: ['华北平原北部', '长江中下游', '青藏高原', '东南沿海'], answer: '华北平原北部', explanation: '北京位于华北平原的北部地区。' },
    { id: 'geo017', category: '历史与地理', difficulty: '中等', question: '一年中的最短的白天一般出现在哪个节气附近？', options: ['冬至', '夏至', '春分', '秋分'], answer: '冬至', explanation: '冬至前后白昼最短、黑夜最长。' },
    { id: 'geo018', category: '历史与地理', difficulty: '中等', question: '我国面积最大的省级行政区是？', options: ['新疆', '西藏', '内蒙古', '青海'], answer: '新疆', explanation: '新疆维吾尔自治区是我国面积最大的省级行政区。' },
    { id: 'geo019', category: '历史与地理', difficulty: '中等', question: '历史上秦始皇统一六国后建立的朝代是？', options: ['秦朝', '汉朝', '唐朝', '宋朝'], answer: '秦朝', explanation: '公元前 221 年秦始皇统一六国，建立秦朝。' },
    { id: 'geo020', category: '历史与地理', difficulty: '中等', question: '《三国演义》主要描写的是哪三个国家之间的故事？', options: ['魏、蜀、吴', '齐、楚、燕', '唐、宋、元', '汉、魏、晋'], answer: '魏、蜀、吴', explanation: '《三国演义》讲述魏、蜀、吴三国鼎立的故事。' },
    { id: 'geo021', category: '历史与地理', difficulty: '中等', question: '唐朝的建立者是？', options: ['李渊', '李世民', '刘邦', '赵匡胤'], answer: '李渊', explanation: '唐朝由唐高祖李渊建立。' },
    { id: 'geo022', category: '历史与地理', difficulty: '中等', question: '我国古代四大发明中，用于印刷的是？', options: ['活字印刷术', '造纸术', '指南针', '火药'], answer: '活字印刷术', explanation: '活字印刷术是四大发明之一，用于印刷。' },
    { id: 'geo023', category: '历史与地理', difficulty: '中等', question: '我国的首都北京位于哪条重要铁路线上？', options: ['京广铁路', '陇海铁路', '成昆铁路', '兰新铁路'], answer: '京广铁路', explanation: '京广铁路连接北京和广州，经过北京。' },
    { id: 'geo024', category: '历史与地理', difficulty: '中等', question: '我国最南端的地级市是？', options: ['三沙市', '海口市', '三亚市', '厦门市'], answer: '三沙市', explanation: '三沙市位于南海，是我国最南端的地级市。' },
    { id: 'geo025', category: '历史与地理', difficulty: '中等', question: '我国的首都北京属于哪个省级行政区？', options: ['北京市', '河北省', '天津市', '河南省'], answer: '北京市', explanation: '北京本身就是一个直辖市（省级行政区）。' },
    { id: 'geo026', category: '历史与地理', difficulty: '中等', question: '历史上的丝绸之路主要是连接中国和哪里的商路？', options: ['欧洲等地', '美洲', '南极洲', '大洋洲'], answer: '欧洲等地', explanation: '丝绸之路是古代连接中国与中亚、欧洲等地的重要商路。' },
    { id: 'geo027', category: '历史与地理', difficulty: '中等', question: '我国的首都北京有哪些著名的世界文化遗产？（选一个）', options: ['故宫和长城', '金字塔', '泰姬陵', '埃菲尔铁塔'], answer: '故宫和长城', explanation: '故宫和长城都是北京著名的世界文化遗产。' },
    { id: 'geo028', category: '历史与地理', difficulty: '中等', question: '郑和下西洋是明朝哪位皇帝在位时期进行的？', options: ['明成祖（永乐）', '明太祖', '明英宗', '明神宗'], answer: '明成祖（永乐）', explanation: '郑和七下西洋主要在明成祖永乐年间进行。' },
    { id: 'geo029', category: '历史与地理', difficulty: '困难', question: '我国的第一座横跨长江的现代化大桥是？', options: ['武汉长江大桥', '南京长江大桥', '江阴长江大桥', '苏通长江大桥'], answer: '武汉长江大桥', explanation: '武汉长江大桥于 1957 年建成，是长江上第一座大桥。' },
    { id: 'geo030', category: '历史与地理', difficulty: '困难', question: '我国的四大名著中，作者是曹雪芹的是？', options: ['《红楼梦》', '《西游记》', '《水浒传》', '《三国演义》'], answer: '《红楼梦》', explanation: '《红楼梦》的作者是清代曹雪芹。' },
    { id: 'geo031', category: '历史与地理', difficulty: '困难', question: '《西游记》中唐僧取经的出发地是？', options: ['长安（今西安）', '洛阳', '南京', '开封'], answer: '长安（今西安）', explanation: '《西游记》中唐僧从唐朝都城长安出发去西天取经。' },
    { id: 'geo032', category: '历史与地理', difficulty: '困难', question: '我国古代"四大发明"不包括下面哪一项？', options: ['瓷器', '造纸术', '火药', '指南针'], answer: '瓷器', explanation: '四大发明是造纸术、印刷术、火药和指南针，瓷器不在其中。' },
    { id: 'geo033', category: '历史与地理', difficulty: '困难', question: '中国历史上第一个统一的中央集权王朝是？', options: ['秦朝', '夏朝', '商朝', '周朝'], answer: '秦朝', explanation: '秦始皇建立的秦朝是我国第一个统一的中央集权王朝。' },
    { id: 'geo034', category: '历史与地理', difficulty: '困难', question: '我国的"四大高原"中，平均海拔最高的是？', options: ['青藏高原', '内蒙古高原', '黄土高原', '云贵高原'], answer: '青藏高原', explanation: '青藏高原平均海拔最高，被称为"世界屋脊"。' },
    { id: 'geo035', category: '历史与地理', difficulty: '困难', question: '我国最大的内流河（不流入海洋的河）是？', options: ['塔里木河', '黄河', '长江', '淮河'], answer: '塔里木河', explanation: '塔里木河是我国最大的内流河，位于新疆。' },
    { id: 'geo036', category: '历史与地理', difficulty: '困难', question: '我国的首都北京所在的时区是？', options: ['东八区', '东一区', '西五区', '东九区'], answer: '东八区', explanation: '北京时间采用东八区时间。' },
    { id: 'geo037', category: '历史与地理', difficulty: '困难', question: '我国最大的岛屿是？', options: ['台湾岛', '海南岛', '崇明岛', '舟山岛'], answer: '台湾岛', explanation: '台湾岛是我国面积最大的岛屿。' },
    { id: 'geo038', category: '历史与地理', difficulty: '困难', question: '《三国演义》中"桃园三结义"的三位人物是？', options: ['刘备、关羽、张飞', '曹操、孙权、刘备', '关羽、赵云、马超', '诸葛亮、周瑜、司马懿'], answer: '刘备、关羽、张飞', explanation: '刘备、关羽、张飞三人在桃园结为兄弟。' },
    { id: 'geo039', category: '历史与地理', difficulty: '困难', question: '我国长江三峡中，最大最著名的是？', options: ['三峡大坝所在的西陵峡', '瞿塘峡', '巫峡', '三峡人家'], answer: '三峡大坝所在的西陵峡', explanation: '西陵峡以三峡大坝闻名，是三峡中最长的一个。' },
    { id: 'geo040', category: '历史与地理', difficulty: '困难', question: '我国大陆海岸线整体大致沿哪个方向延伸？', options: ['东北至西南方向', '西北至东南方向', '正东至正西方向', '没有大致方向'], answer: '东北至西南方向', explanation: '大陆海岸线从东北延伸到西南，整体大致呈东北至西南走向。' },
    /* ================= 英语 KET 基础 30 ================= */
    { id: 'eng001', category: '英语 KET 基础', difficulty: '简单', question: '"苹果"用英语怎么说？', options: ['apple', 'banana', 'orange', 'pear'], answer: 'apple', explanation: '苹果的英文是 apple。' },
    { id: 'eng002', category: '英语 KET 基础', difficulty: '简单', question: '"猫"的英语单词是？', options: ['cat', 'dog', 'bird', 'fish'], answer: 'cat', explanation: '猫是 cat，狗是 dog。' },
    { id: 'eng003', category: '英语 KET 基础', difficulty: '简单', question: '"你好"用英语怎么说？', options: ['hello', 'goodbye', 'sorry', 'thanks'], answer: 'hello', explanation: '你好是 hello 或 hi。' },
    { id: 'eng004', category: '英语 KET 基础', difficulty: '简单', question: '"再见"用英语怎么说？', options: ['goodbye', 'hello', 'yes', 'no'], answer: 'goodbye', explanation: '再见是 goodbye。' },
    { id: 'eng005', category: '英语 KET 基础', difficulty: '简单', question: '"红色"的英语单词是？', options: ['red', 'blue', 'green', 'yellow'], answer: 'red', explanation: '红色是 red，蓝色是 blue。' },
    { id: 'eng006', category: '英语 KET 基础', difficulty: '简单', question: '"谢谢"用英语怎么说？', options: ['thank you', 'please', 'sorry', 'excuse me'], answer: 'thank you', explanation: '谢谢是 thank you。' },
    { id: 'eng007', category: '英语 KET 基础', difficulty: '简单', question: '表示"我"的英语单词是？', options: ['I', 'you', 'he', 'she'], answer: 'I', explanation: '"我"是 I。' },
    { id: 'eng008', category: '英语 KET 基础', difficulty: '简单', question: '"one"表示哪个数字？', options: ['1', '2', '3', '5'], answer: '1', explanation: 'one 表示数字 1。' },
    { id: 'eng009', category: '英语 KET 基础', difficulty: '简单', question: '"蓝色"的英语单词是？', options: ['blue', 'red', 'green', 'black'], answer: 'blue', explanation: '蓝色是 blue。' },
    { id: 'eng010', category: '英语 KET 基础', difficulty: '中等', question: '下面哪个单词表示"书包"？', options: ['bag', 'desk', 'chair', 'book'], answer: 'bag', explanation: 'bag 表示书包或袋子。' },
    { id: 'eng011', category: '英语 KET 基础', difficulty: '中等', question: '"I am ten years old." 的意思是我多少岁？', options: ['十岁', '八岁', '十二岁', '十五岁'], answer: '十岁', explanation: 'ten 表示十，所以是十岁。' },
    { id: 'eng012', category: '英语 KET 基础', difficulty: '中等', question: '表示"我们"的英语单词是？', options: ['we', 'they', 'you', 'it'], answer: 'we', explanation: '"我们"是 we。' },
    { id: 'eng013', category: '英语 KET 基础', difficulty: '中等', question: '"How are you?" 的正确回答是？', options: ['I\'m fine, thank you.', 'I am ten.', 'It is a book.', 'Yes, I do.'], answer: 'I\'m fine, thank you.', explanation: 'How are you? 用 "I\'m fine, thank you." 回答。' },
    { id: 'eng014', category: '英语 KET 基础', difficulty: '中等', question: '"teacher"的中文意思是？', options: ['老师', '学生', '医生', '司机'], answer: '老师', explanation: 'teacher 表示老师。' },
    { id: 'eng015', category: '英语 KET 基础', difficulty: '中等', question: '"three"表示哪个数字？', options: ['3', '2', '4', '6'], answer: '3', explanation: 'three 表示数字 3。' },
    { id: 'eng016', category: '英语 KET 基础', difficulty: '中等', question: '"father"的中文意思是？', options: ['爸爸', '妈妈', '爷爷', '哥哥'], answer: '爸爸', explanation: 'father 表示爸爸，mother 表示妈妈。' },
    { id: 'eng017', category: '英语 KET 基础', difficulty: '中等', question: '"I like apples." 的中文意思是？', options: ['我喜欢苹果', '我不喜欢苹果', '我吃苹果', '我买苹果'], answer: '我喜欢苹果', explanation: 'I like 表示"我喜欢"。' },
    { id: 'eng018', category: '英语 KET 基础', difficulty: '中等', question: '表示"这个"的英语单词是？', options: ['this', 'that', 'these', 'there'], answer: 'this', explanation: '"这个"是 this，\"那个\"是 that。' },
    { id: 'eng019', category: '英语 KET 基础', difficulty: '中等', question: '"He is a doctor." 中 "doctor" 的意思是？', options: ['医生', '教师', '警察', '厨师'], answer: '医生', explanation: 'doctor 表示医生。' },
    { id: 'eng020', category: '英语 KET 基础', difficulty: '中等', question: '"two"表示哪个数字？', options: ['2', '3', '1', '4'], answer: '2', explanation: 'two 表示数字 2。' },
    { id: 'eng021', category: '英语 KET 基础', difficulty: '困难', question: '下面哪句是"I have a new bike."的正确中文翻译？', options: ['我有一辆新自行车', '我有一本新书', '我没有自行车', '我骑自行车'], answer: '我有一辆新自行车', explanation: 'have a new bike 表示有一辆新自行车。' },
    { id: 'eng022', category: '英语 KET 基础', difficulty: '困难', question: '"They are playing football." 中他们在做什么？', options: ['踢足球', '打篮球', '看书', '唱歌'], answer: '踢足球', explanation: 'playing football 表示踢足球。' },
    { id: 'eng023', category: '英语 KET 基础', difficulty: '困难', question: '表示"她"的英语单词是？', options: ['she', 'he', 'it', 'they'], answer: 'she', explanation: '"她"是 she，\"他\"是 he。' },
    { id: 'eng024', category: '英语 KET 基础', difficulty: '困难', question: '"I go to school by bus." 的中文意思是？', options: ['我坐公交车去学校', '我走路去学校', '我坐车回家', '我坐火车去学校'], answer: '我坐公交车去学校', explanation: 'by bus 表示乘坐公交车。' },
    { id: 'eng025', category: '英语 KET 基础', difficulty: '困难', question: '"water"的中文意思是？', options: ['水', '面包', '米饭', '牛奶'], answer: '水', explanation: 'water 表示水。' },
    { id: 'eng026', category: '英语 KET 基础', difficulty: '困难', question: '"She is my sister." 中 "sister" 的意思是？', options: ['姐姐或妹妹', '妈妈', '奶奶', '姑姑'], answer: '姐姐或妹妹', explanation: 'sister 表示姐妹。' },
    { id: 'eng027', category: '英语 KET 基础', difficulty: '困难', question: '"What day is it today?" 是问什么？', options: ['今天是星期几', '今天几号', '今天天气', '今天几点'], answer: '今天是星期几', explanation: 'What day 是问星期几。' },
    { id: 'eng028', category: '英语 KET 基础', difficulty: '困难', question: '"I can swim." 的中文意思是？', options: ['我会游泳', '我喜欢游泳', '我在游泳', '我不想游泳'], answer: '我会游泳', explanation: 'can 表示"会、能"。' },
    { id: 'eng029', category: '英语 KET 基础', difficulty: '困难', question: '"five"表示哪个数字？', options: ['5', '4', '6', '7'], answer: '5', explanation: 'five 表示数字 5。' },
    { id: 'eng030', category: '英语 KET 基础', difficulty: '困难', question: '"The sky is blue." 的中文意思是？', options: ['天空是蓝色的', '天空是白色的', '天空下雨了', '天空是黑色的'], answer: '天空是蓝色的', explanation: 'blue 表示蓝色，句子说天空是蓝色的。' },
    /* ================= 少儿编程与信息科技 25 ================= */
    { id: 'code001', category: '少儿编程与信息科技', difficulty: '简单', question: '在 Scratch 中，积木是按照什么顺序执行的？', options: ['从上到下', '从下到上', '随便乱序', '从中间开始'], answer: '从上到下', explanation: 'Scratch 里脚本通常从上到下依次执行。' },
    { id: 'code002', category: '少儿编程与信息科技', difficulty: '简单', question: '下面哪个是"重复执行"的含义？', options: ['反复做同样的事情', '只做一次', '停下来', '跳过去'], answer: '反复做同样的事情', explanation: '重复执行就是不断循环做同样的事。' },
    { id: 'code003', category: '少儿编程与信息科技', difficulty: '简单', question: '计算机的"CPU"通常被称为什么？', options: ['中央处理器', '显示器', '键盘', '音响'], answer: '中央处理器', explanation: 'CPU 即中央处理器，是电脑的"大脑"。' },
    { id: 'code004', category: '少儿编程与信息科技', difficulty: '简单', question: '下面哪个是用于"条件判断"的积木？', options: ['如果...那么', '重复执行', '移动到', '播放声音'], answer: '如果...那么', explanation: '"如果...那么"用来根据条件决定是否执行。' },
    { id: 'code005', category: '少儿编程与信息科技', difficulty: '简单', question: '"变量"在编程中的作用是什么？', options: ['用来存放数据', '用来发光', '用来发声', '用来移动'], answer: '用来存放数据', explanation: '变量就像一个小盒子，用来存放数据。' },
    { id: 'code006', category: '少儿编程与信息科技', difficulty: '简单', question: '下面哪个设备是"输入设备"？', options: ['键盘', '显示器', '音箱', '打印机'], answer: '键盘', explanation: '键盘把信息输入电脑，是输入设备。' },
    { id: 'code007', category: '少儿编程与信息科技', difficulty: '简单', question: '计算机中，最小的信息单位是？', options: ['位（bit）', '字节（byte）', '千字节', '兆字节'], answer: '位（bit）', explanation: '位（bit）是计算机中最小的信息单位。' },
    { id: 'code008', category: '少儿编程与信息科技', difficulty: '中等', question: '在 Scratch 中，要让角色"如果碰到边缘就反弹"，用哪个积木？', options: ['碰到边缘就反弹', '移动到鼠标', '说你好', '改变颜色'], answer: '碰到边缘就反弹', explanation: '"碰到边缘就反弹"让角色碰到边界时掉头。' },
    { id: 'code009', category: '少儿编程与信息科技', difficulty: '中等', question: '下面哪个积木属于"循环"？', options: ['重复执行', '如果...那么', '等待 1 秒', '播放声音'], answer: '重复执行', explanation: '"重复执行"是循环积木，反复运行内部代码。' },
    { id: 'code010', category: '少儿编程与信息科技', difficulty: '中等', question: '在 Scratch 中，点击绿旗通常用来做什么？', options: ['开始运行程序', '停止程序', '保存程序', '删除角色'], answer: '开始运行程序', explanation: '点击绿旗通常用来启动脚本运行。' },
    { id: 'code011', category: '少儿编程与信息科技', difficulty: '中等', question: '下面哪种做法可以让小猫"移动 10 步"？', options: ['在"移动"积木里填 10', '把小猫删掉', '点红圆', '改变造型'], answer: '在"移动"积木里填 10', explanation: '"移动"积木里的数字表示移动的步数。' },
    { id: 'code012', category: '少儿编程与信息科技', difficulty: '中等', question: '计算机的"硬件"不包括下面哪一项？', options: ['程序代码', '显示器', '键盘', '鼠标'], answer: '程序代码', explanation: '硬件是看得见摸得着的设备，程序代码属于软件。' },
    { id: 'code013', category: '少儿编程与信息科技', difficulty: '中等', question: '在编程中，"如果按下 空格键 就 跳跃"用到了哪种结构？', options: ['条件判断', '无限循环', '顺序执行', '变量赋值'], answer: '条件判断', explanation: '根据按键情况决定是否跳跃，是条件判断。' },
    { id: 'code014', category: '少儿编程与信息科技', difficulty: '中等', question: '"算法"指的是什么？', options: ['解决问题的方法和步骤', '一种游戏', '一种硬件', '一种颜色'], answer: '解决问题的方法和步骤', explanation: '算法就是解决问题的一套明确步骤。' },
    { id: 'code015', category: '少儿编程与信息科技', difficulty: '中等', question: '在 Scratch 中，"播放声音"积木属于哪一类？', options: ['声音', '运动', '外观', '变量'], answer: '声音', explanation: '"播放声音"属于声音类积木。' },
    { id: 'code016', category: '少儿编程与信息科技', difficulty: '中等', question: '下面哪个表示"等待 1 秒"的正确含义？', options: ['程序暂停 1 秒后再继续', '程序加快 1 秒', '程序停止', '程序变慢 10 秒'], answer: '程序暂停 1 秒后再继续', explanation: '"等待 1 秒"让程序暂停 1 秒再往下执行。' },
    { id: 'code017', category: '少儿编程与信息科技', difficulty: '困难', question: '一个循环要执行 5 次，用哪个积木最合适？', options: ['重复执行 5 次', '重复执行（无限）', '如果...那么', '移动 10 步'], answer: '重复执行 5 次', explanation: '"重复执行 5 次"明确指定执行次数。' },
    { id: 'code018', category: '少儿编程与信息科技', difficulty: '困难', question: '在 Scratch 中，"改变颜色效果"属于哪一类积木？', options: ['外观', '运动', '声音', '运算'], answer: '外观', explanation: '改变颜色效果属于外观类积木。' },
    { id: 'code019', category: '少儿编程与信息科技', difficulty: '困难', question: '下列哪种说法正确描述了"事件"？', options: ['当某个动作（如点击）发生时触发程序', '一种颜色', '一种硬件', '一种声音'], answer: '当某个动作（如点击）发生时触发程序', explanation: '事件（如点击绿旗、按下按键）用来触发程序运行。' },
    { id: 'code020', category: '少儿编程与信息科技', difficulty: '困难', question: '要让小猫"碰到边缘就反弹，且不上下颠倒"，通常需要搭配哪个积木？', options: ['将旋转方式设为左右翻转', '删除小猫', '改变大小', '播放音乐'], answer: '将旋转方式设为左右翻转', explanation: '左右翻转可以让角色上下不颠倒。' },
    { id: 'code021', category: '少儿编程与信息科技', difficulty: '困难', question: '在编程中，"3 + 5" 用"运算"积木算出结果，应该选哪个？', options: ['8', '35', '2', '15'], answer: '8', explanation: '3 + 5 的结果是 8。' },
    { id: 'code022', category: '少儿编程与信息科技', difficulty: '困难', question: '下面哪个积木可以用来"让角色说一句话"？', options: ['说...', '移动...', '等待...', '播放声音'], answer: '说...', explanation: '"说..."积木让角色显示一句对话框文字。' },
    { id: 'code023', category: '少儿编程与信息科技', difficulty: '困难', question: '在 Scratch 中，要让程序"当绿旗被点击时开始"，应使用哪个积木？', options: ['当绿旗被点击', '当按下空格', '当角色被点击', '当背景切换'], answer: '当绿旗被点击', explanation: '"当绿旗被点击"是常用的开始事件。' },
    { id: 'code024', category: '少儿编程与信息科技', difficulty: '困难', question: '下列哪项属于"顺序结构"的特点？', options: ['按先后顺序一步步执行', '反复执行', '根据条件选择执行', '同时执行所有积木'], answer: '按先后顺序一步步执行', explanation: '顺序结构就是按顺序从上到下执行。' },
    { id: 'code025', category: '少儿编程与信息科技', difficulty: '困难', question: '在 Scratch 中，要"将 x 坐标增加 10"，属于哪类积木？', options: ['运动', '外观', '声音', '控制'], answer: '运动', explanation: '改变坐标属于运动类积木。' },
  ];
});
